spring.application.name=demo

# setting up things
# it is non-java file which stores data in key:value format
# it is configuration file

#paymentGateway.type=paytm
#paymentGateway.retry-count=5

# adding values for PaymentProperties file
#canonical names requirement
payment-property.type=paytm
payment-property.retry-count=5
payment-property.enabled=true
payment-property.timeout=3000
