spring.application.name=crudSpringBootDemo

# db setup & all

spring.datasource.url=jdbc:postgresql://localhost:5432/student_crud_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# create table auto by the fields
spring.jpa.hibernate.ddl-auto=update
# to see queries in our log we need to true this field as by default this is false
spring.jpa.show-sql=true
# to see queries in formatted way
spring.jpa.properties.hibernate.format_sql=true

