# things that are we don't want to keep hardcoded in our code, that we write in config file
# local environment
spring.application.name=profileDemo

# PostgreSQL Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/student_crud_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres123

# making profiling
app.welcome.message=LOCAL: Hello, welcome to my application

app.welcome.code=200
app.welcome.names=Aditya,Roshan,Mahesh,Rohan

# to envoke and notify SpringBoot about the profiles we use special key as
#spring.profiles.active=prod
# here it loads properties from both dev profile(profile specific) and also common application.properties config file

