# things that are we don't want to keep hardcoded in our code, that we write in config file
spring.application.name=profileDemo

# changing server port from 8080(default) to 9090 : existing Spring Boot configuration
server.port=9090

# PostgreSQL Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/student_crud_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres123

app.welcome.message=LOCAL: Hello, welcome to my application